on: push
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      id: ftp-deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.projetoscti.com.br
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        protocol: ftp
        server-dir: '/uninews/'
        log-level: 'standard'  # Valid log-level value
        timeout: 1200  # Increased timeout to 20 minutes
        security: 'strict'  # Use 'loose' if strict does not work
        state-name: 'ftp-state.json'  # Save state to handle retries

    - name: Retry on failure
      if: ${{ failure() }}
      run: |
        echo "Retrying FTP deployment..."
        for i in {1..3}; do
          echo "Attempt $i..."
          if SamKirkland/FTP-Deploy-Action@v4.3.5 \
            server=ftp.projetoscti.com.br \
            username=${{ secrets.username }} \
            password=${{ secrets.password }} \
            protocol=ftp \
            server-dir=/uninews \
            log-level=standard \
            timeout=1200 \
            security=strict \
            state-name=ftp-state.json; then
            echo "Deployment succeeded on attempt $i"
            break
          else
            echo "Attempt $i failed, retrying..."
            sleep 30
          fi
        done
