on: push
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      id: ftp-deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.projetoscti.com.br
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        protocol: ftps
        local-dir: './local-path'
        server-dir: '/remote-path'
        log-level: 'info'
        timeout: 1200  # Increased timeout to 20 minutes
        security: 'strict'  # Use 'loose' if strict does not work
        state-name: 'ftp-state.json'  # Save state to handle retries

    - name: Retry on failure
      if: ${{ failure() }}
      run: |
        echo "Retrying FTP deployment..."
        retry --max-attempts=3 -- sleep 30 && \
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.projetoscti.com.br
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          protocol: ftps
          local-dir: './local-path'
          server-dir: '/remote-path'
          log-level: 'info'
          timeout: 1200  # Increased timeout to 20 minutes
          security: 'strict'  # Use 'loose' if strict does not work
          passive: true  # Enable passive mode
          state-name: 'ftp-state.json'  # Save state to handle retries
          max-retries: 3  # Number of retries in case of failure
